### ISSUE TITLE
KeyError: 'data'

### ISSUE THREAD

**Issue by drigoni** [XiangChenchao/DDPN#2]
Dear authors, 
I have downloaded your code and set it as the repository indicate. 
I was able to compile caffe, pycaffe and to set the environments variables.
However, when I try to extract the  flickr30k images features, I get the following error which I am not able to resolve.

Linux command:
`
drigoni@drigoni-Precision-3630-Tower:~/repository/DDPN$ python ./tools/extract_feat.py --gpu 0 --cfg ./config/experiments/flickr30k-kld-bbox_reg.yaml --def ./data/flickr30k/pretrained_model/flickr30k/test.prototxt --net ./data/flickr30k/pretrained_model/flickr30k/final.caffemodel --img_dir ./data/flickr30k/flickr30k-images/ --out_dir ./data/flickr30k/features/bottom-up-feats/ --num_bbox 100,100 --feat_name pool5_flat
`
Output:
`
Called with args:
Namespace(caffemodel='./data/flickr30k/pretrained_model/flickr30k/final.caffemodel', cfg_file='./config/experiments/flickr30k-kld-bbox_reg.yaml', feat_name='pool5_flat', gpu_id='0', img_dir='./data/flickr30k/flickr30k-images/', num_bbox='100,100', outpath='./data/flickr30k/features/bottom-up-feats/', prototxt='./data/flickr30k/pretrained_model/flickr30k/test.prototxt', set_cfgs=None)
Using config:
{'ANNO_PATH': './data/flickr30k/format_%s.pkl',
 'BATCHSIZE': 64,
 'DATA_DIR': '/home/drigoni/repository/DDPN/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'default',
 'FEAT_DIR': './data/flickr30k/features/bottom-up-feats',
 'GPU_ID': 0,
 'IMAGE_DIR': './data/flickr30k/flickr30k-images',
 'IMDB_NAME': 'flickr30k',
 'MATLAB': 'matlab',
 'MODELS_DIR': '/home/drigoni/repository/DDPN/models/pascal_voc',
 'NTHREADS': 16,
 'PIXEL_MEANS': array([[[102.9801, 115.9465, 122.7717]]]),
 'PROJ_NAME': 'genome_kld_reg',
 'QUERY_DIR': './data/flickr30k/query_dict',
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/drigoni/repository/DDPN',
 'TEST': {'AGNOSTIC': False,
          'BBOX_REG': True,
          'HAS_ATTRIBUTES': False,
          'HAS_RELATIONS': False,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'selective_search',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'SCALES': [600],
          'SOFT_NMS': 0,
          'SVM': False},
 'TRAIN': {'AGNOSTIC': False,
           'ASPECT_GROUPING': True,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': False,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.1,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'HAS_ATTRIBUTES': False,
           'HAS_RELATIONS': False,
           'HAS_RPN': False,
           'IMS_PER_BATCH': 2,
           'MAX_ITERS': 100000,
           'MAX_SIZE': 1000,
           'MIN_RELATION_FRACTION': 0.25,
           'PROPOSAL_METHOD': 'selective_search',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 16,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'RPN_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'RPN_NORMALIZE_TARGETS': False,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_ITERS': 5000,
           'STEPSIZE': 40000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False,
           'VALIDATE_INTERVAL': 5000},
 'USE_GPU_NMS': True,
 'USE_KLD': True,
 'USE_REG': True}
Process Process-1:
`
Traceback:
`
Traceback (most recent call last):
  File "/home/drigoni/programs/miniconda/envs/frcnn_vg/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/drigoni/programs/miniconda/envs/frcnn_vg/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./tools/extract_feat.py", line 134, in generate_npz
    features, bbox, image_h, image_w, num_bbox = get_feats_from_im(net, im, min_max_bboxes, feat_name)
  File "./tools/extract_feat.py", line 41, in get_feats_from_im
    scores, boxes, attr_scores, rel_scores = im_detect(net, im)
  File "/home/drigoni/repository/DDPN/tools/../lib/fast_rcnn/test.py", line 145, in im_detect
    net.blobs['data'].reshape(*(blobs['data'].shape))
KeyError: 'data'
`
if I am correct, it seems the model is not able to find the key `data` in `net.blobs`.
Using the print command I checked that the folders/files used in the parameters are correct. In fact, I am using your pre-trained model for flickr30k and its prototxt file.
What do I have to do in order to fix it?

Thank you for your help.
Davide

**Comment by drigoni** [comment]
Dear all, finally I have solved it.
I was loading a wrong file .prototxt. 
Just follow this repository to get the features: https://github.com/peteanderson80/bottom-up-attention
